### PR TITLE
Update introduction.md

### PR DESCRIPTION
**Pull request by donkizzy**
There was a spelling error

### CODE REVIEW

**Comment by praveenweb** [comment]
Hi @donkizzy - Thanks for your PR :)

`grok` was used intentionally since it means `to understand`. Tagging @mehtavishwa30 to see if this will become part of langauage improvements.

**Comment by donkizzy** [comment]
Hi @praveenweb  I didn't know `grok` was an actual word
thanks

**Comment by praveenweb** [comment]
Closing this PR :)

**Comment by mehtavishwa30** [comment]
Hi @donkizzy, thanks for bringing this up.

Since the word `grok` is only informally used in the US, replacing it with a more universally known word will be made part of our ongoing language enhancements for more inclusive and universal use of language.

cc: @praveenweb

**Pull request closed without merging**
