### PR TITLE
fixed typos, markdown

### PR DESCRIPTION
**Pull request by DevMike123**
Added some required markdown and fixed typos.

### CODE REVIEW

**Comment by DevMike123** [comment]
@praveenweb can you review the pr?

**Comment by DevMike123** [comment]
@hasura can you consider this pr as hacktoberfest submission provide me the prize link as mentioned in the guidelines?

**Comment by praveenweb** [comment]
@DevMike123 - We do appreciate your contribution, however, we’re committed to prioritizing quality contributions that address an issue as outlined in our most up-to-date [blog](https://hasura.io/blog/with-hasura-celebrate-open-source-in-style-with-hacktoberfest/). I'm afraid this PR doesn't qualify for the "hacktoberfest-accepted" label.

**Comment by DevMike123** [comment]
> @DevMike123 - We do appreciate your contribution, however, we’re committed to prioritizing quality contributions that address an issue as outlined in our most up-to-date [blog](https://hasura.io/blog/with-hasura-celebrate-open-source-in-style-with-hacktoberfest/). I'm afraid this PR doesn't qualify for the "hacktoberfest-accepted" label.

@praveenweb  it's mentioned in the blog that pr for typo fix will qualify for sticker pack.

**Pull request merged**
