### PR TITLE
added coc

### LINKED ISSUE #780: Add Code of Conduct and Issue Templates
@praveenweb

### PR DESCRIPTION
**Pull request by MrKrishnaAgarwal**
cc @praveenweb 
closes #780

### CODE REVIEW

**Comment by MrKrishnaAgarwal** [comment]
@praveenweb please review

**Comment by praveenweb** [comment]
@MrKrishnaAgarwal - Hey, thanks for the PR. In the interest of keeping the messaging consistent, we want to reuse the code of conduct from the https://github.com/hasura/graphql-engine repo. Will you be able to port that content over here, and I can merge that?

**Comment by MrKrishnaAgarwal** [comment]
@praveenweb I'll make the requested changes soon!

**Comment by MrKrishnaAgarwal** [comment]
@praveenweb Done!

**Comment by MrKrishnaAgarwal** [comment]
Will I get Hasura Hacktoberfest Swags?

**Pull request closed without merging**
