### PR TITLE
bring apollo-angular boilerplate/final-project/tutorial to Angular 10, fix #293, #228

### LINKED ISSUE #228: Angular Tutorial breaks on "Run mutation, update cache" page
Everything works just fine up until [this page](https://hasura.io/learn/graphql/angular-apollo/mutations-variables/3-create-mutation/), specifically complaining that:

`Property 'insert_todos' does not exist on type '{}'`

and: 

` Property 'loading' does not exist on type 'ExecutionResult<{}> & { extensions?: Record<string, any>; context?: Record<string, any>; }'.`

### LINKED ISSUE #293: angular-apollo project - final app won't compile
This project starts to compile and progresses to close to 80% before throwing this error: 

src/app/OnlineUsers/OnlineUsersWrapper.ts:60:31 - error TS2339: Property 'loading' does not exist on type 'ExecutionResult<{}> & { extensions?: Record<string, any>; context?: Record<string, any>; }'.

the boilerplate version does the same thing when you get part way through the lesson.

### PR DESCRIPTION
**Pull request by hirenchauhan2**
#293 was due to missing field `loading`  from the result of `subscribe` passed to the function. Also, there were more issues like this. Have fixed all of them :100:

**Update:**

- [x] Migrated the project to Angular 10 🚀  
- [x] Updated the final-app, boilerplate, tutorial content
- [x] Updated `apollo-angular`, `@apollo/client`, and code related to new updates
- [x] Added type for new todo returning the result.
- [x] Code formatted across the project.. that's why multiple files in the commit :raised_hands:
- [x] Removed the `"name"` from `@Input("name") name` as this is automatically figured out by Angular if both names are the same.
- [x] Also, fixes #228, #293   

~~I tried to migrate to this project to Angular's latest stable version 10 but there are some issues with the Apollo-Angular package that need to be resolved.~~

### CODE REVIEW

**Comment by praveenweb** [comment]
@hirenchauhan2 - Thanks for the PR. I tested the updated app and it seems to compile and function. Haven't looked at the code yet, but this seems good so far.

Broadly I see that this PR has updated code (app-final). The corresponding tutorial content will need a similar update if required. Will you be able to take that up as well?

**Comment by hirenchauhan2** [comment]
Hi @praveenweb, thanks for checking out my code!

> Broadly I see that this PR has updated code (app-final). The corresponding tutorial content will need a similar update if required. Will you be able to take that up as well?

Yes, I would love to do that 💯 

I can see that the following places where changes are required:
-  tutorials/frontend/angular-apollo/app-boilerplate
-  tutorials/frontend/angular-apollo/tutorial-site/content   (adding explicit versions while installing the packages for graphql things -- should be updated in future when all the modules are compatible with 10 version) + typescript code

Let me know if you think I missed something.

I will update those places and push the commits.

**Comment by praveenweb** [comment]
@hirenchauhan2 - Updates to those two places (app-boilerplate and content) should wrap up this PR 👍 
Let me know if you need any help.

**Comment by hirenchauhan2** [comment]
Hi @praveenweb,

I have updated all the required contents for the angular 10 upgrade.
Let me know how this looks!

**Comment by praveenweb** [comment]
@hirenchauhan2 - Hey, will check this soon and post an update (hopefully will merge and release)

**Comment by mehtavishwa30** [comment]
This is a lovely contribution, @hirenchauhan2! Thanks so much for spending your time and efforts on improving our Learn course and congratulations on getting your PR merged to Hasura. 🎉

Looking forward to more such contributions from you! ✨

**Pull request merged**
