### PR TITLE
Updated Subscription method

### PR DESCRIPTION
**Pull request by subhendukundu**
It helpful for people who follow the documentation, if we keep it updated. I have updated the method based on the new changes in the package.

### CODE REVIEW

**Comment by praveenweb** [comment]
@subhendukundu - Will you be able to make the respective change in the codebase as well? Right now you have suggested a change in the course content and I'm not sure if packages need to be updated as well.

**Comment by subhendukundu** [comment]
@praveenweb Sure I would do that. Sorry for the delay, forgot about this PR.

**Comment by subhendukundu** [comment]
I dont think we need to change in the codebase. It just changes of using the package. Please let me know if you want me to look at anything specifically.

**Comment by subhendukundu** [comment]
ahh! forgot about this. Thank you @praveenweb 
Will try to update few of the docs for flutter coming days.

**Comment by praveenweb** [comment]
@subhendukundu - That would be so nice 👍 

Will trigger a deployment soon with a bunch of changes that got merged now.

**Pull request merged**
