### PR TITLE
Convert Class Components to Functional components

### LINKED ISSUE #68: Migrate class components to functional components
All components except `Testimonials.js` just have a render method. They don't use any special stuff which class components provide. Since there is a transpilation cost associated with class components, we should use function components instead.

Note- I'm not talking about adding hooks in the project. The only place where a hook would be useful is `Testimonials.js` but it is fine its current state. I'm just talking about other components which don't need hooks

### PR DESCRIPTION
**Pull request by deadcoder0904**
Closes #68

### CODE REVIEW

**Comment by praveenweb** [comment]
@deadcoder0904 - Doesn't render the components. The usage of `props` needs to be updated since class components has been moved to functional.

**Comment by deadcoder0904** [comment]
Ohh sorry 😂Forgot to do that. Brb

**Comment by deadcoder0904** [comment]
@praveenweb okay done. check again :)

**Comment by deadcoder0904** [comment]
bdw can u add `hacktoberfest` label to the issue

**Pull request merged**
