### PR TITLE
Upgrade react tutorial to use Apollo v3

### PR DESCRIPTION
**Pull request by kriswep**
Update the `react-apollo-hooks` tutorial to use apollo v3 as suggested in #190 

Note: apollo v3 is still in RC, so I'm using these versions. Tell me, if you want to wait for the final release.

What changed:
- [X] Use new apollo lib `@apollo/client` and `@apollo/link-ws` instead of `apollo-boost`, `@apollo/react-hooks` and `apollo-link-ws`
- [X] Changed the used libs in `app-final`
- [X] Changed the description and code blocks in `tutorial-site`

### CODE REVIEW

**Comment by praveenweb** [comment]
@kriswep - This looks good. Thanks for taking this up 👍 

The only thing I want to verify before merging - how the usage of Cache has changed from v2 to v3. I know it's backward compatible. But the patterns around handling cache might have changed. (Haven't looked at the details yet). I will post an update soon.

Also, we can keep this PR open and merge it once v3 stable is released.

**Comment by kriswep** [comment]
Sounds good. Can update to the final versions, once they are released.

The cache handling can stay unchanged. Apollo recommends to use readQuery and writeQuery, which is what we already do here. See the cache section in the [migration guide]https://www.apollographql.com/docs/react/v3.0-beta/migrating/apollo-client-3-migration/#breaking-cache-changes).
On top of that, they added some advanced functionality for garbage collection and cache eviction.

**Comment by kriswep** [comment]
🎉 [Apollo v3](https://www.apollographql.com/blog/announcing-the-release-of-apollo-client-3-0/) was released this week. Yeah.

I updated this PR:
- Resolved conflicts
- switched to the final apollo v3 version, which now includes `@apollo/link-ws`

This should be good to be merged now!

**Comment by praveenweb** [comment]
@kriswep - Just tested this with the latest changes. Works as expected 🎉 

Merging and deploying now 👍

**Pull request merged**
