### PR TITLE
Update apollo-client.md

### LINKED ISSUE #349: Schema download returns 404
Hello!

I tried to download the schema by using my own access token. However, it returns **404**:

> apollo client:download-schema OUTPUT --endpoint=http://hasura.io/learn/graphql --header="Authorization: Bearer MY_OWN_ACCESS_TOKEN".

> Project": Error: ServerError: Response not successful: Received status code 404

Any help is greatly appreciated!

### PR DESCRIPTION
**Pull request by Akshay-Nagle**
Fixes #349 Schema download returns 404

### CODE REVIEW

**Comment by Akshay-Nagle** [comment]
@praveenweb Please review my PR

**Comment by praveenweb** [comment]
Hi @Akshay-Nagle - Thanks for the fix! `https` is the working version.

**Comment by Akshay-Nagle** [comment]
@praveenweb sir, please add relevant tags like hacktoberfest and hacktoberfest-accepted

**Comment by Akshay-Nagle** [comment]
@praveenweb Sir by when can I receive swags for participating in Hacktoberfest?

**Comment by mehtavishwa30** [comment]
Hey @Akshay-Nagle! Thanks for contributing to Hasura Learn. Could you please share your email id so that I can share the swag form to you?

**Comment by Akshay-Nagle** [comment]
Mam, my email: akshay_1901cb06@iitp.ac.in

> Hey @Akshay-Nagle! Thanks for contributing to Hasura Learn. Could you please share your email id so that I can share the swag form to you?

**Comment by mehtavishwa30** [comment]
> Mam, my email: [akshay_1901cb06@iitp.ac.in](mailto:akshay_1901cb06@iitp.ac.in)
> 
> > Hey @Akshay-Nagle! Thanks for contributing to Hasura Learn. Could you please share your email id so that I can share the swag form to you?

Thanks @Akshay-Nagle! You should receive an email with the swag form shortly! :)

Cheers!

**Pull request merged**
